name: Run Python Script Daily

on:
  schedule:
    # Run daily at midnight (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      script_mode:
        description: "Specify the script mode (e.g., test or production)"
        required: true
        default: "test"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check directory structure
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing files:"
          ls -al
    
      - name: Debug folder structure
        run: |
          echo "Listing root directory:"
          ls -al /
          echo "Listing runner workspace:"
          ls -al /home/runner/work
          echo "Listing runner project directory:"
          ls -al /home/runner/work/QuantumQuestor
          echo "Listing runner repo directory:"
          ls -al /home/runner/work/QuantumQuestor/QuantumQuestor
        
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          pwd
          python -m pip install --upgrade pip
          pip install -r keyword_generator/requirements.txt

      # Run the Python script
      - name: Run script
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          RAPIDAPI_HOST: ${{ secrets.RAPIDAPI_HOST }}
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          keyword_generator/fetch_keywords.py
