name: Run Python Script Daily

on:
  schedule:
    # Run weekly on Monday at 4 PM UTC
    - cron: '0 15 * * 1'
  workflow_dispatch:
    inputs:
      script_mode: # Define an input parameter
        description: "Specify the script mode (e.g., test or production)"
        required: true
        default: "test"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          pwd
          python -m pip install --upgrade pip
          pip install -r keyword_generator/requirements.txt

      - name: Make the script executable
        run: chmod +x keyword_generator/fetch_keywords.py

      # Run the Python script
      - name: Run script
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          RAPIDAPI_HOST: ${{ secrets.RAPIDAPI_HOST }}
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: |
          python keyword_generator/fetch_keywords.py

