name: Run Article Generation

on:
  schedule:
    # Run weekly on Monday at 4 PM UTC
    - cron: '0 16 * * 1'
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      script_mode: # Define an input parameter
        description: "Specify the script mode (e.g., test or production)"
        required: true
        default: "test"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Adjust version if needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r article_generation/requirements.txt

      # Step 4: Add secrets to the environment
      - name: Run Article Generation Script
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WORDPRESS_CLIENT_ID: ${{ secrets.WORDPRESS_CLIENT_ID }}
          WORDPRESS_CLIENT_SECRET: ${{ secrets.WORDPRESS_CLIENT_SECRET }}
          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
          WORDPRESS_SITE_URL: ${{ secrets.WORDPRESS_SITE_URL }}
        run: |
          echo "Environment variables configured."
          python article_generation/generate_articles.py
